feat: add the about dex modal
aeternity/dex-ui pull request #414
Opened 2022-07-26 18:47 UTC by bogdan-manole

Fixes #313

2022-07-29 06:31 UTC, kenodressel commented on src/components/AboutModal.vue
> +    :title=" $t('aboutModal.title') "
why the spaces?

2022-07-29 06:31 UTC, kenodressel commented on src/components/AboutModal.vue
> +      this.height = await sdk.height();
should we update this in an interval?

2022-07-29 10:08 UTC, bogdan-manole commented on src/components/AboutModal.vue
> +      this.height = await sdk.height();
done

2022-07-29 10:08 UTC, bogdan-manole commented on src/components/AboutModal.vue
> +    :title=" $t('aboutModal.title') "
done

2022-08-01 07:29 UTC, kenodressel approved these changes

2022-08-01 07:30 UTC, CedrikNikita commented
Adjustments:
- fix warnings
`Should not import the named export 'version' (imported as 'contractsVersion') from default-exporting module (only default export is available soon)`
- fix: show compiler url
- simplify scss and markup
- without await while sdk trully, if user opens fast enough, no depending on sdk information will be presented
- get height before setting an interval so user won't wait till we firstly get it
- increase polling interval, height is not changing that fast (can be even more increased)

2022-08-01 07:31 UTC, CedrikNikita requested changes
Commits should be squashed before merge

2022-08-01 11:39 UTC, bogdan-manole commented
@CedrikNikita 

> * fix warnings
>   `Should not import the named export 'version' (imported as 'contractsVersion') from default-exporting module (only default export is available soon)`

done

> * fix: show compiler url

what's wrong with it?
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3176255/182140024-f308187a-c071-4a09-bc99-05aa10deb19b.png">

> * simplify scss and markup

I need more details. This is a modified version of ConfirmLiquidityModal.vue

> * without await while sdk trully, if user opens fast enough, no depending on sdk information will be presented

done (take a look)

> * get height before setting an interval so user won't wait till we firstly get it

done
> * increase polling interval, height is not changing that fast (can be even more increased)

done (set to 15 secs, if you are thinking on sth else please make a suggestion)

2022-08-03 12:47 UTC, kenodressel reviewed
some padding on the left column would be nice so the "dex backend" is not directly merging into the url.
![image](https://user-images.githubusercontent.com/765921/182611273-4721f77f-6b75-4897-a5f3-a6403c39b54f.png)

2022-08-06 00:44 UTC, CedrikNikita commented
> some padding on the left column would be nice so the "dex backend" is not directly merging into the url.

done

2022-08-08 07:40 UTC, kenodressel approved these changes

2022-08-08 07:41 UTC, kenodressel approved these changes

2022-08-08 08:09 UTC, CedrikNikita approved these changes

2022-08-08 08:09 UTC, merged